server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petshome?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000ms

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # 解决Swagger与Spring Boot 2.7.x的兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.petshome.api.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    root: info
    com.petshome.api: debug
    org.springframework: info

# 自定义配置
petshome:
  # JWT配置
  jwt:
    # JWT加解密使用的密钥
    secret: petshome-secret-key
    # JWT的超期限时间(60*60*24*7)
    expiration: 604800
  # 上传配置
  upload:
    # 本地文件存储配置
    local:
      upload-dir: uploads
      url-prefix: http://localhost:8080/api/uploads/
    # 阿里云OSS配置
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: your-access-key-id
      access-key-secret: your-access-key-secret
      bucket-name: petshome
      url-prefix: https://petshome.oss-cn-beijing.aliyuncs.com/