server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petshome?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 30000

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms

  # 解决Swagger与Spring Boot 2.7.x的兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.petshome.api.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 自定义项目配置
petshome:
  # JWT令牌配置
  jwt:
    secret: petshome-secret-key
    expiration: 86400 # 24小时
  # 文件上传配置
  upload:
    # 阿里云OSS配置
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: your-access-key-id
      access-key-secret: your-access-key-secret
      bucket-name: petshome-bucket
      url-prefix: https://petshome-bucket.oss-cn-beijing.aliyuncs.com/