server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/petshome?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  
  # Redis配置 
  redis:
    host: localhost
    port: 6379
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# 日志配置
logging:
  level:
    com.petshome.api: info
    org.springframework: warn
  file:
    path: /var/log/petshome 